name = "NewtonsMethod"
uuid = "10b45fad-5cd8-4ec7-aa26-3da463956760"
authors = ["loforteg <giulialoforte@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
